---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: dockerkey
    instance_type: t2.micro
    image: "ami-0f9ce67dcf718d332"
    region: us-east-1
    user_access_key: "AKIAYXA54GIOPDMDAY4H"
    user_secret_key: "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"

  tasks:
    - name: startup new instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         aws_access_key: "{{ user_access_key }}"
         aws_secret_key: "{{ user_secret_key }}"
      register: ec2
      
    - debug:
        var: ec2.instances[0].public_ip
