---
# this playbook for tags example
# command to execute: ansible-playbook tags.yml --tags first
- name: tags
  hosts: master
  tasks:
    - name:
      file:
        state: touch
        path: /home/ansible/{{ item }}
        with_items:
          - file_no_1
          - file_no_2
          - file_no_3
      tags: first

    - name: "Install Common Libraries from CentOS mirror"
      yum: state=present name={{ item }}
      with_items:
        - sudo
        - vim
        - gcc
        - gcc-c++
        - autoconf
        - tar
       tags: second
       
     - debug:
        msg: "this is third taks"
      tags: third
